### PR TITLE
Bugfix and improvements to Sanity Client

### PR DESCRIPTION
**Pull request by rvanoord**
### Bugfixes

1. [JsonProperty("_id")] attribute was added to Id field of ISanityDoc, since this is the default for Id in Sanity now. Without this, a null exception was thrown when checking for draft documents, since Id field was null.

> Note: Drafts can also be filtered using a query: `!(_id in path(\"drafts.**\"))" : "")` which would probably be more efficient than post-filtering.

### Improvements:

1. Added a new Query function. This is almost identical to Fetch, but does not require that the result is an array, meaning it can be used to retrieve not-array results, such as a "count" query or a single field.
2. Removed requirement for implementing ISanityDoc. Instead, ISanityDoc may be still be used for optimal performance, but the client will also use a conventions to find the Id field on any type (using reflection). This implementation should also be quite fast since the reflected types/properties are cached.
3. Reorganized ordering of methods

> There are no known breaking changes.

### CODE REVIEW

**Review by onybo — COMMENTED** [review]
Thanks for helping out!
I like your idea about allowing for more options with respect to naming of the Id property (Improvement 2). I also see that it may be useful to differentiate between a single result and an array (Improvement 1). I initially thought that an array of 1 is good enough, but I am fine with adding a specific method for the single value case.

Improvement 3 will not be accepted though. I follow the principle of placing methods in the order they are used as described by Rober C. Martin in his book Clean Code. 
https://stackoverflow.com/questions/1760850/best-practice-ordering-of-public-protected-private-within-the-class-definition.
As a member of the http://anti-region-legion.org/ it is of my opinion that #regions are a big "no no" :-)

I believe that the bug (missing JsonProperty("_id")) isn't really a bug. It was intentionally left out as there is nothing stopping you from adding this attribute to the property in your class which is implementing the interface, and then it should work. Maybe I should document this better.

I would like you to split the PR into 2 smaller PRs as I think it would be easier to discuss.

PR 1: "Query function for single values"
I think we should consider if the naming can be improved. Now we have Fetch and Query.
I am not sure that these two names conveys the difference. I.e. that Fetch returns an array and Query a single value.
Maybe FetchMultiple and FetchSingle is better? Or something else?

PR2: "Remove requirement for implementing ISanityDoc"
I like the idea, but I think it can be improved if we rather than this:
doc.GetDocumentId()?.StartsWith("drafts.")).GetValueOrDefault(false)

Do something like this:
doc.IsDraftDocument()

We also need to look at the namespace of the extensions. I think it may be annoying to some users if we add extensions methods to object when using the Olav.Sanity.Client namespace. 
Maybe if we put the extensions in Olav.Sanity.Client.Internals namespace it would be better?

**Comment by rvanoord** [comment]
Thanks for the feedback. I will create two new pull-requests as suggested.

### Method naming
I didn't quite like the comination of "Fetch" and "Query" either, but chose not to change "Fetch" to avoid breaking changes. I choose "Query" for general purpose queries because this reflects the naming in the Sanity documentation and also because it is not exclusively used to return a "single" result - the result could be any projection and potentially also an array. Maybe Fetch could be renamed to GetDocuments(). 

Is there a reason for not suffixing the asynchronous methods with Async, i.e. GetDocumentAsync(), FetchAsync() etc?

### Return type
It might be a consideration to have a single return type instead of a tupple, for backwards compatiblity. This is obviously a breaking change.

### Bug?
Agree that omitting the JsonProperty("_id") attribute wasn't a bug. The underlying bug was a missing null-check, which caused a runtime exception if Id was null and excludeDrafts flag was true. I like the suggestion to use doc.IsDraftDocument() extension and will implement this in the new pull-requests.

**Comment by onybo** [comment]
**Method naming**
I think that if we keep both they should be named similarl. "Fetch" and "Query" are identical except for the number of of results it is important that the name reflects this. 
Both are really Sanity queries.
As you say "Query" can do all types of queries depending. And so can "Fetch", maybe we don´t need two?
What if this is just naming? I.e. maybe we could just rename Fetch to Query, and rename the type FetchResult type to your QueryResult. 
That is only this:
`public class QueryResult<T>
    {
        public int Ms { get; set; }
        public string Query { get; set; }
        public T Result { get; set; }
    }`
Then we avoid any confusion of which one to use.

About Async postfix I like the reasoning given here: https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

**Comment by rvanoord** [comment]
As far as I can see, Fetch expects an array response, whereas Query expects any type of object (which could also be an array). 
Fetch also has the option of checking for drafts, since the expected response is documents. That's why I've suggested renaming Fetch to GetDocuments which is consistent with the extisting GetDocument method.

**Pull request closed without merging**
