### PR TITLE
Feature/method renames without async

### PR DESCRIPTION
**Pull request by rvanoord**
Same as #6 , but without Async method suffix

### CODE REVIEW

**Comment by onybo** [comment]
I am not happy with the naming.
We now have two methods that will do a query.
The general one, named Fetch/GetDocuments which I believe should almost always be used.
Almost every Sanity query may return any number of results (default from 0 to 100).
Only very special queries such as some aggregate functions like count() are guaranteed to return only a single document.
I can't see many situations where it would be safe to use the current Query function. 
Except when it is used with an array as the type parameter, and in this case it becomes a Fetch/GetDocuments with the only difference that it can't filter drafts.
The use of the Query function as it is, may lead to bugs where the developer assumes that the query should only return a single document while in fact the actual Sanity query may return any number of documents. 
Naming the Query function "Query" would lead a new user to think that the Query function is the most appropriate for general Queries, while it is actually Fetch/GetDocuments that should be the default method to use when doing Sanity queries. 

I would suggest the following naming:
Query - Fetch an array of documents or values using a GROQ query. Note that only documents can be filtered by draft status (excludeDrafts: true)
QuerySingle - Fetch a single object result using a GROQ query. Typical examples include aggregate queries such as count()

**Comment by rvanoord** [comment]
As far as I can see Fetch/GetDocuments is just a special case of Query where the return type is restricted to an array.

I feel that _Query should actually be the default_ (without placing any restriction on the return type) because of the the explaination provided in the Sanity documentation (ref. https://www.sanity.io/docs/http-api/http-query):

> **Caveat**: It is a common mistake to assume that the result is an array of documents, but it isn't. It can be any valid JSON value. If the query is *[_id=="myId"][0], the result is the document object unwrapped, for count(*[_type == 'actor' && name match 'weaver']) the result will be a number. If the query is *[_type == 'actor'].name, the result is an array of strings (given that the names are strings).

From this description, it would seem that "QuerySingle" is also somewhat misleading, because the result may be a document / projection, not necessarily just a single primative value.

As you pointed out in another pull-request, I forgot to remove the "excludeDrafts" parameter from QueryResultToResult, so that can certainly be removed. I think it would normally be more effective to exclude drafts using a server side query rather than post-filtering on the client side.

However, at the end of the day, as long as both functions are available, I'm happy to go with whatever naming.

**Comment by onybo** [comment]
going for the Query and QuerySingle. At least for now.
@rvanoord : thanks a lot for all the PRs and inputs. New version is published to nuget.org (0.1.1)

**Comment by rvanoord** [comment]
Thanks @onybo!

**Pull request closed without merging**
